plugins {
    alias(libs.plugins.kotlin.jvm)
}

class Names(val words: Array<String>) {
    constructor(name: String) : this(name.split('-').toTypedArray())
    val lodash get() = words.joinToString("_")
    val kebab get() = words.joinToString("-")
    val upperCamel get() = words.joinToString("") { word -> word.replaceFirstChar { it.uppercase() } }
}

fun basePluginClassPackage(names: Names) = "vip.cdms.allaymc.kotlinx.shared.${names.lodash}"
fun basePluginClassName(names: Names) = "Kotlinx${names.upperCamel}SharedLib"
fun basePluginClass(names: Names) = """
    |package ${basePluginClassPackage(names)}
    |
    |import org.allaymc.api.plugin.Plugin
    |
    |/** Automatically generated. Do NOT edit this file directly! */
    |class ${basePluginClassName(names)} : Plugin()
    |
""".trimMargin()

fun basePluginDescriptor(names: Names) = """
    {
      "entrance": "${basePluginClassPackage(names)}.${basePluginClassName(names)}",
      "name": "kotlinx-${names.kebab}-lib",
      "description": "${
          if (names.lodash == "kotlinx") "Kotlin-style Extension Library for Allay Server"
          else "Kotlinx Shared Library for Allay Server -- ${names.upperCamel}"
      }",
      "authors": [
        "MineBuilder"
      ],
      "version": "${'$'}{version}",
      "dependencies": [],
      "website": "https://github.com/MineBuilders/allaymc-kotlinx"
    }
""".trimIndent()

subprojects {
    val names = Names(name)
    if (names.lodash == "build" || names.words.getOrNull(1) == "generated") return@subprojects

    val generatePath = arrayOf("build", "plugin-generated-$name")
    val generateDir = File(projectDir, "../" + generatePath.joinToString("/")).apply { mkdirs() }
    val sourceDir = File(generateDir, "src/main/kotlin/" + basePluginClassPackage(names).split('.').joinToString("/"))
    val resourcesDir = File(generateDir, "src/main/resources")
    File(sourceDir.apply { mkdirs() }, basePluginClassName(names) + ".kt").writeText(basePluginClass(names))
    File(resourcesDir.apply { mkdirs() }, "plugin.json").writeText(basePluginDescriptor(names))

    plugins.apply(rootProject.libs.plugins.kotlin.jvm.get().pluginId)
    plugins.apply(rootProject.libs.plugins.gradleup.shadow.get().pluginId)
    version = rootProject.rootProject.version
    afterEvaluate {
        dependencies { implementation(project(":plugin:" + generatePath.joinToString(":"))) }
        kotlin { jvmToolchain(21) }
    }
}
