name: Build a preview plugin

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout master
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew :plugin:shadowJar
          ./gradlew :plugin:compose-lib:shadowJar

      - name: Rename jar
        run: |
          mv "plugin/build/libs/plugin-all.jar" "plugin/build/libs/kotlinx-${{ github.sha }}.jar"
          mv "plugin/compose-lib/build/libs/compose-lib-all.jar" "plugin/build/libs/kotlinx-compose-${{ github.sha }}.jar"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: kotlinx-shared-lib-plugin-${{ github.sha }}
          path: plugin/build/libs/kotlinx-${{ github.sha }}.jar

      - name: Upload artifact (Compose)
        uses: actions/upload-artifact@v4
        with:
          name: kotlinx-compose-shared-lib-plugin-${{ github.sha }}
          path: plugin/build/libs/kotlinx-compose-${{ github.sha }}.jar
